#!/usr/bin/env python3
"""Audit and lift the ten-position unique-tail cover survivor.

The fixed labels from ``unique_tail_forced_common_atoms_attack.py`` are first
closed under every quotient-zero star of total length 2..8.  The same closure
is generated by two independent enumerators.  Every locally visible internal
subset of every induced zero-core F3 complement is then checked against the
complete axial atom criterion, and all locally decidable intersection gates
are checked.

There are two independent obstructions.

* The published fixed labels do not give the declared set U its required
  unique-tail sum, and they induce one forbidden length-seven family-one star.
* More strongly, even arbitrary relabelling cannot preserve the displayed
  incidence table together with the unified quotient labels.  Any two of the
  three singleton-trace complements force a quotient-zero star of length
  p-b+1 in the forbidden interval 9..p+1.

Thus no completion by external positions can lift this particular local
skeleton.  This is not an UNSAT result for any packing type, or for the full
unique-tail branch.
"""

from __future__ import annotations

from collections import Counter
from itertools import combinations
import hashlib
import json


PRIME_TYPES = ((233, 7, 4), (1399, 8, 5))
POSITION_ORDER = (
    "u1",
    "u2",
    "u3",
    "v1",
    "v2",
    "v3",
    "w1",
    "w2",
    "y",
    "z",
)
POSITION_VALUES = {
    "u1": (0, 1, 0, 0),
    "u2": (0, 0, 1, 0),
    "u3": (0, 1, 1, 0),
    "v1": (1, -1, -2, 1),
    "v2": (1, -2, -1, 1),
    "v3": (1, -1, -1, 1),
    "w1": (0, 0, 2, 0),
    "w2": (0, 2, 0, 0),
    "y": (0, 3, 4, 0),
    "z": (-2, -3, -4, 1),
}
U = frozenset(("u1", "u2", "u3"))
Q_SINGLETON = {
    "s1": frozenset(("u2", "u3", "v1")),
    "s2": frozenset(("u1", "u3", "v2")),
    "s3": frozenset(("u1", "u2", "v3")),
}
Q_ENDPOINT = {
    **Q_SINGLETON,
    "d1": frozenset(("u1", "v1", "w1")),
    "d2": frozenset(("u2", "v2", "w2")),
}
LENGTH_FAMILIES = {
    2: (1,),
    3: (1,),
    4: (1, 2),
    5: (1, 2),
    6: (1, 2, 3),
    7: (2, 3),
    8: (3,),
}
EXPECTED_CERTIFICATE_SHA256 = (
    "4d5da443323c68e487a8f98b898d6aa3bd649a1fa9b2edbf369bb5e822b0295c"
)


def canonical_hash(value: object) -> str:
    payload = json.dumps(
        value, ensure_ascii=True, sort_keys=True, separators=(",", ":")
    ).encode("ascii")
    return hashlib.sha256(payload).hexdigest()


def vector_sum(names: tuple[str, ...] | frozenset[str], p: int) -> tuple[int, ...]:
    return tuple(
        sum(POSITION_VALUES[name][coordinate] for name in names) % p
        for coordinate in range(4)
    )


def record_for(mask: int, core_count: int, p: int) -> dict[str, object] | None:
    tail = tuple(
        name for index, name in enumerate(POSITION_ORDER) if mask >> index & 1
    )
    total_length = len(tail) + core_count
    if total_length not in LENGTH_FAMILIES:
        return None
    total = vector_sum(tail, p)
    quotient = ((total[0] + core_count) % p, total[1], total[2])
    if quotient != (0, 0, 0):
        return None
    actual_family = total[3]
    allowed = LENGTH_FAMILIES[total_length]
    return {
        "tail": list(tail),
        "tail_mask": mask,
        "core_count": core_count,
        "length": total_length,
        "actual_sum_multiple_of_a": actual_family,
        "allowed_family_multiples": list(allowed),
        "status": "ACCEPTED" if actual_family in allowed else "REJECTED",
    }


def enumerate_short_mask(p: int, available_core: int | None = None) -> list[dict[str, object]]:
    maximum_core = p - 4 if available_core is None else available_core
    rows: list[dict[str, object]] = []
    for mask in range(1 << len(POSITION_ORDER)):
        tail_size = mask.bit_count()
        for core_count in range(min(maximum_core, 8 - tail_size) + 1):
            row = record_for(mask, core_count, p)
            if row is not None:
                rows.append(row)
    return sorted(rows, key=lambda row: (row["length"], row["core_count"], row["tail_mask"]))


def enumerate_short_naive(p: int) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for tail_size in range(len(POSITION_ORDER) + 1):
        for tail in combinations(POSITION_ORDER, tail_size):
            mask = sum(1 << POSITION_ORDER.index(name) for name in tail)
            for core_count in range(min(p - 4, 8 - tail_size) + 1):
                row = record_for(mask, core_count, p)
                if row is not None:
                    rows.append(row)
    return sorted(rows, key=lambda row: (row["length"], row["core_count"], row["tail_mask"]))


def short_closure(p: int) -> dict[str, object]:
    rows = enumerate_short_mask(p)
    assert rows == enumerate_short_naive(p)
    rejected = [row for row in rows if row["status"] == "REJECTED"]
    accepted = [row for row in rows if row["status"] == "ACCEPTED"]
    assert len(rows) == 14
    assert len(rejected) == 1
    expected_bad = {
        "u2",
        "u3",
        "w1",
        "w2",
        "z",
    }
    bad = rejected[0]
    assert set(bad["tail"]) == expected_bad
    assert (bad["length"], bad["core_count"], bad["actual_sum_multiple_of_a"]) == (
        7,
        2,
        1,
    )
    assert bad["allowed_family_multiples"] == [2, 3]

    # The bad row is the unique local short-window failure.  It disappears
    # after deleting any one of its five tail positions, or after retaining
    # fewer than two X positions.
    deletion_counts = {}
    for removed in sorted(expected_bad):
        index = POSITION_ORDER.index(removed)
        remaining_bad = [
            row
            for row in rows
            if row["status"] == "REJECTED" and not (row["tail_mask"] >> index & 1)
        ]
        deletion_counts[removed] = len(remaining_bad)
    assert set(deletion_counts.values()) == {0}
    reduced_core_bad = [
        row for row in enumerate_short_mask(p, available_core=1)
        if row["status"] == "REJECTED"
    ]
    assert not reduced_core_bad

    family_counts = Counter(
        f"F{row['actual_sum_multiple_of_a']}" for row in accepted
    )
    return {
        "candidate_count": len(rows),
        "accepted_count": len(accepted),
        "rejected_count": len(rejected),
        "accepted_family_counts": dict(sorted(family_counts.items())),
        "rows": rows,
        "unique_rejected_row": bad,
        "naive_crosscheck": "PASS",
        "inclusion_minimality": {
            "bad_tail_position_deletion_remaining_failure_counts": deletion_counts,
            "with_only_one_X_position_remaining_failure_count": len(reduced_core_bad),
        },
    }


def f3_name(tail: frozenset[str]) -> str:
    local_remainder = frozenset(POSITION_ORDER) - tail
    for name, q_set in Q_ENDPOINT.items():
        if local_remainder == q_set:
            return name
    if local_remainder == frozenset(("u3", "v3")):
        return "d3_auto"
    raise AssertionError((tail, local_remainder))


def local_internal_subsets(
    local_remainder: frozenset[str], core_count: int, p: int
) -> tuple[list[dict[str, object]], list[dict[str, object]]]:
    ordered = tuple(name for name in POSITION_ORDER if name in local_remainder)
    rows: list[dict[str, object]] = []
    for size in range(1, len(ordered) + 1):
        for subset in combinations(ordered, size):
            total = vector_sum(subset, p)
            if total[1:3] != (0, 0):
                continue
            coefficient = total[0]
            rows.append(
                {
                    "subset": list(subset),
                    "q_axis_coefficient": coefficient,
                    "allowed_by_axial_atom_gate": coefficient in range(1, core_count + 4),
                }
            )

    # Independent submask generation of exactly the same axial rows.
    direct: list[dict[str, object]] = []
    for mask in range(1, 1 << len(ordered)):
        subset = tuple(ordered[index] for index in range(len(ordered)) if mask >> index & 1)
        total = vector_sum(subset, p)
        if total[1:3] == (0, 0):
            direct.append(
                {
                    "subset": list(subset),
                    "q_axis_coefficient": total[0],
                    "allowed_by_axial_atom_gate": total[0] in range(1, core_count + 4),
                }
            )
    direct.sort(key=lambda row: (len(row["subset"]), row["subset"]))
    rows.sort(key=lambda row: (len(row["subset"]), row["subset"]))
    assert rows == direct
    return rows, [row for row in rows if not row["allowed_by_axial_atom_gate"]]


def derived_f3_audit(p: int, closure: dict[str, object]) -> dict[str, object]:
    f3_rows = [
        row for row in closure["rows"]
        if row["status"] == "ACCEPTED" and row["actual_sum_multiple_of_a"] == 3
    ]
    assert len(f3_rows) == 6
    records = []
    total_internal = 0
    total_axial = 0
    total_violations = 0
    for row in f3_rows:
        assert row["core_count"] == 0
        tail = frozenset(row["tail"])
        remainder = frozenset(POSITION_ORDER) - tail
        axial, violations = local_internal_subsets(remainder, 0, p)
        subset_count = (1 << len(remainder)) - 1
        total_internal += subset_count
        total_axial += len(axial)
        total_violations += len(violations)
        records.append(
            {
                "name": f3_name(tail),
                "tail": row["tail"],
                "trace_on_U": sorted(tail & U),
                "local_complement_slice": sorted(remainder),
                "all_nonempty_local_internal_subsets_checked": subset_count,
                "axial_internal_subsets": axial,
                "axial_gate_violations": violations,
            }
        )
    records.sort(key=lambda row: row["name"])
    assert total_internal == 38
    assert total_axial == 6
    assert total_violations == 0
    return {
        "derived_zero_core_F3_count": len(records),
        "records": records,
        "local_internal_subset_count": total_internal,
        "local_axial_subset_count": total_axial,
        "local_axial_gate_violation_count": total_violations,
        "scope_boundary": (
            "Every internal subset contained entirely in L minus the F3 tail is checked. "
            "Subsets using R cannot be formed because the old survivor assigned no unified "
            "q-axis/a-coordinate labels to the individual R positions."
        ),
    }


def intersection_audit(p: int, closure: dict[str, object]) -> dict[str, object]:
    accepted = [row for row in closure["rows"] if row["status"] == "ACCEPTED"]
    f3 = [row for row in accepted if row["actual_sum_multiple_of_a"] == 3]
    disjoint_required_pair_count = 0
    disjoint_conflicts = []
    for left_index, left in enumerate(accepted):
        left_tail = set(left["tail"])
        for right in accepted[left_index + 1:]:
            right_tail = set(right["tail"])
            gate_applies = (
                left["actual_sum_multiple_of_a"] == 3
                or right["actual_sum_multiple_of_a"] == 3
                or left["actual_sum_multiple_of_a"] == right["actual_sum_multiple_of_a"] == 2
            )
            if not gate_applies:
                continue
            disjoint_required_pair_count += 1
            if left_tail.isdisjoint(right_tail):
                disjoint_conflicts.append([left["tail"], right["tail"]])

    f3_pairs = []
    zero_quotient_count = 0
    axial_count = 0
    for left_index, left in enumerate(f3):
        for right in f3[left_index + 1:]:
            common = frozenset(left["tail"]) & frozenset(right["tail"])
            total = vector_sum(tuple(common), p)
            if total[:3] == (0, 0, 0):
                zero_quotient_count += 1
            axial = total[1:3] == (0, 0)
            if axial:
                axial_count += 1
            f3_pairs.append(
                {
                    "left": f3_name(frozenset(left["tail"])),
                    "right": f3_name(frozenset(right["tail"])),
                    "intersection": sorted(common),
                    "intersection_quotient_sum": list(total[:3]),
                    "axis_only": axial,
                }
            )
    assert not disjoint_conflicts
    assert len(f3_pairs) == 15
    assert zero_quotient_count == 0
    assert axial_count == 3
    return {
        "short_block_pairs_subject_to_tail_intersection_gate": disjoint_required_pair_count,
        "tail_intersection_gate_violation_count": len(disjoint_conflicts),
        "F3_pair_count": len(f3_pairs),
        "F3_pair_zero_quotient_intersection_count": zero_quotient_count,
        "F3_pair_axis_only_intersection_count": axial_count,
        "F3_pairs": f3_pairs,
    }


def fixed_tail_identity(p: int, length: int, b: int) -> dict[str, object]:
    observed = vector_sum(tuple(sorted(U)), p)
    expected = ((-b) % p, 0, 0, 3)
    assert observed != expected
    return {
        "unique_type": [length, b],
        "declared_U": sorted(U),
        "observed_actual_sum": list(observed),
        "required_actual_sum": list(expected),
        "status": "REJECTED",
    }


def formal_incidence_difference(
    left: frozenset[str], right: frozenset[str], subtract: frozenset[str]
) -> frozenset[str]:
    coefficients = Counter(left)
    coefficients.update(right)
    coefficients.subtract(subtract)
    assert all(value in (0, 1) for value in coefficients.values())
    return frozenset(name for name, value in coefficients.items() if value == 1)


def unified_label_lift_obstruction(p: int, length: int, b: int) -> dict[str, object]:
    witnesses = []
    for left, right in combinations(sorted(Q_SINGLETON), 2):
        tail = formal_incidence_difference(Q_SINGLETON[left], Q_SINGLETON[right], U)
        assert len(tail) == 3
        core_count = p - b - 2
        total_length = len(tail) + core_count
        assert 0 <= core_count <= p - 4
        assert 9 <= total_length <= p + 1
        assert total_length == p - b + 1
        # sigma_bar(Q_left)+sigma_bar(Q_right)-sigma_bar(U)
        # = q+q-(-bq)=(b+2)q, cancelled by p-b-2 copies of q.
        assert (b + 2 + core_count) % p == 0
        witnesses.append(
            {
                "singleton_endpoint_pair": [left, right],
                "forced_tail": sorted(tail),
                "forced_tail_q_axis_coefficient": b + 2,
                "X_core_count": core_count,
                "quotient_zero_length": total_length,
                "forbidden_interval": [9, p + 1],
            }
        )
    assert len(witnesses) == 3
    return {
        "status": "UNSAT_FOR_EVERY_RELABEL_AND_EVERY_EXTERNAL_COMPLETION",
        "quantifier": (
            "For every assignment of labels to the ten named positions and every external "
            "completion R, if U has quotient sum -bq, each displayed singleton complement "
            "Q_si has quotient sum q, and X contains p-4 copies of q, then each pair of "
            "singleton complements forces the listed forbidden quotient-zero block."
        ),
        "witnesses": witnesses,
        "assumptions_used": [
            "U={u1,u2,u3} and quotient_sum(U)=-bq",
            "the displayed incidence sets Q_s1,Q_s2,Q_s3",
            "quotient_sum(Q_si)=q",
            "X supplies at least p-b-2 copies of q",
            "no quotient-zero block has length in 9..p+1",
        ],
        "assumptions_not_used": [
            "actual a-coordinate sums",
            "projected atom minimality of Q_H or P_i",
            "which of the three forced packing types is used",
            "F3 complement internal subset sums",
            "Hasse rows",
            "actual Z atomicity",
        ],
    }


def hasse_boundary(p: int) -> dict[str, object]:
    local_positions = len(POSITION_ORDER)
    point_scalar_rows = 3 * (1 + local_positions)
    pair_keys = 1 + local_positions + local_positions * (local_positions - 1) // 2
    triple_keys = (
        1
        + local_positions
        + local_positions * (local_positions - 1) // 2
        + local_positions * (local_positions - 1) * (local_positions - 2) // 6
    )
    return {
        "status": "NOT_REACHED_AFTER_FORCED_BLOCK_CONTRADICTION",
        "local_fixed_point_scalar_rows": point_scalar_rows,
        "local_fixed_pair_scalar_rows": 2 * pair_keys,
        "local_fixed_triple_scalar_rows": triple_keys,
        "reason": (
            "These rows also receive contributions from blocks using R.  The old survivor "
            "does not label R position by position, and external contributions cannot remove "
            "either forced quotient-zero obstruction."
        ),
        "prime": p,
    }


def build_certificate() -> dict[str, object]:
    instances = []
    for p, length, b in PRIME_TYPES:
        closure = short_closure(p)
        instances.append(
            {
                "p": p,
                "unique_type": [length, b],
                "fixed_tail_identity": fixed_tail_identity(p, length, b),
                "fixed_label_short_closure": closure,
                "derived_F3_local_internal_subsets": derived_f3_audit(p, closure),
                "locally_decidable_intersections": intersection_audit(p, closure),
                "unified_label_relabelling_obstruction": unified_label_lift_obstruction(
                    p, length, b
                ),
                "hasse_boundary": hasse_boundary(p),
            }
        )
    return {
        "status": (
            "TEN_POSITION_SKELETON_NOT_LIFTABLE/"
            "FIXED_LABEL_SHORT_CORE/UNIFIED_LABEL_RELABEL_CORE/"
            "NO_PACKING_TYPE_CLOSED/GLOBAL_INCOMPLETE"
        ),
        "scope": (
            "The exact ten-position incidence skeleton of the explicit local survivor, for "
            "p=233 and p=1399.  The result quantifies over every relabelling and every external "
            "completion of this skeleton, but not over other endpoint incidence skeletons."
        ),
        "instances": instances,
        "global_boundary": (
            "This kills one deliberately relaxed local witness.  It does not prove any of the "
            "seven common-R packing types empty, does not close the large-prime unique-tail "
            "branch, and is not an A_p theorem or counterexample."
        ),
    }


def main() -> None:
    certificate = build_certificate()
    certificate_hash = canonical_hash(certificate)
    if EXPECTED_CERTIFICATE_SHA256:
        assert certificate_hash == EXPECTED_CERTIFICATE_SHA256
    print(
        json.dumps(
            {**certificate, "certificate_sha256": certificate_hash},
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
